# Generated by Django 6.0.3 on 2026-04-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='icon',
            field=models.CharField(default='📖', help_text='Emoji icon for the lesson circle', max_length=10),
        ),
    ]
