# Generated by Django 6.0.3 on 2026-04-27 16:31

from django.db import migrations, models


def backfill_is_completed(apps, schema_editor):
    """Existing responses are treated as locked-in: a correct first attempt is also "completed",
    and an incorrect one stays uncompleted (the user will be given a retry under the new rules)."""
    UserResponse = apps.get_model('soft_skills', 'UserResponse')
    UserResponse.objects.filter(is_correct=True).update(is_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('soft_skills', '0002_add_lesson_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has eventually answered correctly (first attempt or any retry). Drives lesson completion and the progress bar.'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(help_text='Whether the user picked the correct option on their FIRST attempt. Never changes after row creation.'),
        ),
        migrations.RunPython(backfill_is_completed, reverse_code=migrations.RunPython.noop),
    ]
