# Generated by Django 6.0.3 on 2026-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_skills', '0003_userresponse_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_answer_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_answer_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
