# Generated by Django 6.0.3 on 2026-06-10 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_skills', '0004_userprofile_current_answer_streak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='soft_skills.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medalla asignada',
                'verbose_name_plural': 'Medallas asignadas',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
