# Generated by Django 6.0.3 on 2026-07-11 17:24

import django.core.validators
import soft_skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_skills', '0005_badgeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gamification_level_admin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nulo'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], default=soft_skills.models.default_gamification_level, verbose_name='Nivel de gamificación (admin/recomendado)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gamification_level_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Nulo'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], null=True, verbose_name='Nivel de gamificación (usuario)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocean_agreeableness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Amabilidad (A)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocean_conscientiousness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Responsabilidad (C)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocean_extraversion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Extraversión (E)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocean_neuroticism',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Neuroticismo (N)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocean_openness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Apertura (O)'),
        ),
    ]
